Rename all dist/*.js to dist/*.cjs
Error:
```
Error:  AssertionError [ERR_ASSERTION]: ifError got unwanted exception: require() of ES Module /usr/src/app/migrations/20220614111600-make-subjects-in-construction-a-subject.js from /usr/src/app/node_modules/db-migrate/lib/skeleton.js not supported.
20220614111600-make-subjects-in-construction-a-subject.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename 20220614111600-make-subjects-in-construction-a-subject.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /usr/src/app/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```